name: Release & Publish

on:
    release:
        types:
            - published

permissions:
  contents: read

jobs:
    validate:
        runs-on: ubuntu-latest
        steps:
            - name: Harden Runner
              uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
              with:
                egress-policy: audit

            - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
            - name: Validate package.json version matches release tag
              run: |
                VERSION=$(cat package.json | jq -r .version)
                if [ "v$VERSION" != "${GITHUB_REF/refs\/tags\//}" ]; then
                  echo "Version mismatch: package.json version is $VERSION, but release tag is ${GITHUB_REF/refs\/tags\//}"
                  exit 1
                fi
    publish:
        runs-on: ubuntu-latest
        needs: validate
        permissions:
          contents: read
          packages: write
        steps:
            - name: Harden Runner
              uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
              with:
                egress-policy: audit

            - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
            - name: Setup .npmrc file to publish to npm
              uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
              with:
                node-version: '20.x'
                registry-url: 'https://registry.npmjs.org'
                scope: '@hiddenlayerai'
            - name: Install modules
              run: npm install --legacy-peer-deps
            - name: Build
              run: npm run build
            - name: Prune modules
              run: npm prune --production --legacy-peer-deps
            - name: Publish to npm
              run: npm publish --access public
              env:
                NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
            - name: Setup .npmrc to publish to GitHub Packages
              uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
              with:
                node-version: '20.x'
                registry-url: 'https://npm.pkg.github.com'
            - name: Publish to GitHub Packages
              run: npm publish --access public
              env:
                NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
